### PR TITLE
Child Process: stream stderr/out to a log file

### LINKED ISSUE #12: Cryptic 504 Reported when a child process is missing
[`child-process--log-output`](https://github.com/iFixit/multi-user-dev-server/compare/child-process--log-output)

### Problem

When a child process is missing the parent process hard fails!

We try to [send a message to the child](https://github.com/iFixit/multi-user-dev-server/blob/master/webpack-watcher.js#L41), but the child is MIA. This causes an Error which is caught, then [passed through as a 504](https://github.com/iFixit/multi-user-dev-server/blob/master/multi-user-dev-server.js#L130-L132)

### Stack trace
```js
Error: channel closed
   at ChildProcess.target.send (internal/child_process.js:584:16) at Promise (/mnt/ebs/home/ifixit/Code/Exec/AssetBuild/node_modules/multi-user-dev-server/webpack-watcher.js:41:16)
   at Object.whenDone (/mnt/ebs/home/ifixit/Code/Exec/AssetBuild/node_modules/multi-user-dev-server/webpack-watcher.js:39:23)
   at app.post (/mnt/ebs/home/ifixit/Code/Exec/AssetBuild/node_modules/multi-user-dev-server/multi-user-dev-server.js:117:61)
   at Layer.handle [as handle_request] (/mnt/ebs/home/ifixit/Code/Exec/AssetBuild/node_modules/express/lib/router/layer.js:95:5)
   at next (/mnt/ebs/home/ifixit/Code/Exec/AssetBuild/node_modules/express/lib/router/route.js:137:13)
   at e (/mnt/ebs/home/ifixit/Code/Exec/AssetBuild/node_modules/multi-user-dev-server/multi-user-dev-server.js:77:20)
   at Layer.handle [as handle_request] (/mnt/ebs/home/ifixit/Code/Exec/AssetBuild/node_modules/express/lib/router/layer.js:95:5)
   at next (/mnt/ebs/home/ifixit/Code/Exec/AssetBuild/node_modules/express/lib/router/route.js:137:13)
   at Route.dispatch (/mnt/ebs/home/ifixit/Code/Exec/AssetBuild/node_modules/express/lib/router/route.js:112:3)
```

### Do This

* Gracefully retry / restart the build if this situation occurs
* Potentially - has a child record why it died?

### PR DESCRIPTION
**Pull request by danielbeardsley**
* Allow users of this module to specify a log file that
  should receive stdout / stderr from the webpack process
   * If it crashes, we'll actually have the output
* If the webpack proc crashes, notify the watchers
* Respond quickly if trying to ask the child a question
  when it's dead.

CC @jarstelfox

Closes #12

### CODE REVIEW

File: webpack-watcher.js [hunk 1]
```diff
@@ -43,7 +44,27 @@ module.exports = (options) => {
...
+      const forkOptions = getForkOptions();
+      const child = childProcess.fork(__dirname + '/webpack-compiler.js', forkOptions)
+      logOutput(child)
+      return child;
+   }
+
+   function getForkOptions() {
+      const output = options.logPath ? 'pipe' : 'inherit';
+      return {
+         stdio: ['inherit', output, output, 'ipc']
```
Comment (davidrans) [inline webpack-watcher.js:66]: I read the docs here, and I don't understand when/why this should be an array of 4 things (as opposed to 3, in/out/err)? https://nodejs.org/api/child_process.html#child_process_options_stdio

Comment (danielbeardsley) [reply webpack-watcher.js:66]: > (for `.fork()`) When this option is provided, it overrides `silent`. If the array variant is used, it must contain exactly one item with value 'ipc' or an error will be thrown. For instance [0, 1, 2, 'ipc'].

**Comment by jarstelfox** [comment]
CR 🌵

File: webpack-watcher.js [hunk 2]
```diff
@@ -38,10 +39,46 @@ module.exports = (options) => {
       },
       whenDone: () => new Promise((resolve, reject) => {
          watchers.add({resolve, reject});
-         child.send({event: 'isRunning'})
+         if (child.connected) {
+            child.send({event: 'isRunning'})
+         } else {
+            notifyWatchers("Webpack child process crashed, check the log");
```
Comment (sctice) [inline webpack-watcher.js]: Could we use `options.logPath` to point people directly at the log and _not_ suggest checking the log if `options.logPath` is falsey?

File: webpack-watcher.js [hunk 3]
```diff
@@ -38,10 +39,46 @@ module.exports = (options) => {
...
+
+      options.log = fs.createWriteStream(options.logPath, {flags: "a"});
+      child.stdout.pipe(options.log);
+      child.stderr.pipe(options.log);
+   }
+
+   function listenForExit(child) {
+      child.on('exit', function(code) {
+         console.log("Process for " + options.username + " stopped with exit code: " + code);
+         notifyWatchers("Webpack child process crashed, check the log");
```
Comment (sctice) [inline webpack-watcher.js]: Same note here about using `options.logPath`.

**Comment by sctice** [comment]
CR 🎏 but deploy_block ✋ on considering a suggestion.

**Comment by danielbeardsley** [comment]
un_deploy_block 👍   Good suggestions!

File: webpack-watcher.js (hunk 3 above)
Comment (danielbeardsley) [reply webpack-watcher.js]: Fixed.

File: webpack-watcher.js (hunk 2 above)
Comment (danielbeardsley) [reply webpack-watcher.js]: Fixed.

**Comment by danielbeardsley** [comment]
Note we still suggest checking the log cause the output will be in the log of the parent process.

**Comment by jarstelfox** [comment]
CR 🌵

**Comment by k0rvusk0r4x** [comment]
Not a clue how to test this. Ideas?

Also, this is not showing up on Pulldasher but a pull is deploy blocked on it.

**Comment by jarstelfox** [comment]
CR 🌵

**Comment by danielbeardsley** [comment]
I'll post some screenshots of the webpack logs that we get now

Syntax error:
image

Module not found:
image

Webpack config error:
image

Messages when builds fail:
image

The client now sees this for many of the errors:
image

QA 👍 

I've also added this to pulldasher.
